#logging.level.org.apache.coyote.http11=debug
#spring.messages.basename=messages,errors
#
#spring.devtools.livereload.enabled=true
#spring.devtools.remote.restart.enabled=false
#spring.freemarker.cache = false
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#
server:
  servlet:
    session:
      tracking-modes=cookie: cookie
      timeout: 1800
#session:
#  setMaxInactiveInterval: 1800

spring:

  messages:
    basename: messages,errors

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??
        highlight_sql: true # SQL ??? ANSI escape codes? ???? ?? ?????.
        use_sql_comments: true
# ???????? ?? ??? ?? ???? in-memory? ???? ???? ??.
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  #?? ??? ????? ??? ?? ????? ??? ???.

